"""
Django settings for AMALTools project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = r'^a1r%o))lk^8*%!d*_za4x#g%1p%y72@)j9kcdg88tovm@@5+w'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True


MAINTENANCE_MODE = False

ALLOWED_HOSTS = ['127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'converters',
    'maths',
    'miscellaneous',
    'fileconverters',
    'users',
    'othertools',
    'programming',
]
# AMALTools_app.middleware.WwwRedirectMiddleware From https://adamj.eu/tech/2020/03/02/how-to-make-django-redirect-www-to-your-bare-domain/
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'miscellaneous.middleware.WwwRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'miscellaneous.middleware.TesterMiddleware',
    # 'miscellaneous.middleware.MaintenencePageMiddleware',
    # 'users.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'miscellaneous.middleware.PageViewsMiddleware',

]

ROOT_URLCONF = 'AMALTools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AMALTools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db.sqlite3',
   }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-uk'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'
#STATIC_ROOT = BASE_DIR / 'static_files'

STATICFILES_DIRS = [
    BASE_DIR / "static_files",
]


STATIC_ROOT = BASE_DIR / 'static'

STATIC_URL = 'static/' 

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#because http (set up https!!)
# CSRF_TRUSTED_ORIGINS = ['http://amaltools-env.eu-west-2.elasticbeanstalk.com/','http://amaltools.com','http://www.amaltools.com']

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

SESSION_COOKIE_HTTPONLY = True

# AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend'] #,'users.backends.SecretTesterBackend'



# # REQUIRED FOR DEPLOYMENT (according to python manage.py check --deploy)

# # PRODUCTION SETTINGS, COMMENT OUT FOR LOCAL TESTING
# # Production database

# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     'NAME': '',
#     'USER': '',
#     'PASSWORD': '',
#     'HOST': 'localhost',
#     'PORT': '',
#   }
# }

# # uncomment next four lines once website is https

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 0

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "Level: {levelname}-{asctime}-{module}-{process:d}-{thread:d} Error: {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "file": {
#             "level": "INFO",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/django.log",
#             "formatter": "verbose",
#         },
#         "file_debug": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs/django_debug.log",
#             "formatter": "verbose",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file"],
#             "level": "INFO",
#         },
#         "django.debug": {
#             "handlers": ["file_debug"],
#             "level": "DEBUG",
#         },
#     },
# }

# # Celery settings
# CELERY_BROKER_URL = "redis://localhost:6379"
# CELERY_RESULT_BACKEND = "redis://localhost:6379"
# CELERY_TIMEZONE = TIME_ZONE

# CELERYD_PID_FILE = BASE_DIR / "celery/celeryd.pid"
# CELERYD_LOG_FILE = BASE_DIR / "logs/celeryd.log"
# CELERYD_LOG_LEVEL = "INFO"